import { Roboto_Mono } from 'next/font/google';
import './globals.css';
import Header from './components/header';
import Footer from './components/footer';


const robotoMono = Roboto_Mono({
  weight: ['100', '400', '700'], // Adjust weights as needed
  subsets: ['latin'],
  variable: '--font-roboto-mono', 
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoMono.variable} antialiased`}>
      <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
